### ISSUE TITLE
Include JS/CSS as files directly.

### ISSUE THREAD

**Issue by Telavian** [Overmiind/Puppeteer-sharp-extra#1]
Looking through the source code it is actually really hard to read because the JS is loaded from resources.
The current resource file seems to have been removed also.

One possible solutions would be to include the JS directly in their own JS file, mark as embedded resource, and load using similar code below.

Maybe there is a better way however having the JS files directly would make a lot of things easier.

``` C#
_jsFile1 ??= LoadResource("Full.Qualified.Name.Of.JS.js");

        protected static string LoadResource(string name)
        {
            var assembly = typeof(xyz).Assembly;

            using (var stream = assembly.GetManifestResourceStream(name))
            {
                if (stream == null)
                {
                    throw new Exception($"Unable to load resource matching name {name}.");
                }

                using (var reader = new StreamReader(stream))
                {
                    return reader.ReadToEnd();
                }
            }
        }   
```

**Comment by Overmiind** [comment]
Hi, thank you for your feedback, you're right. I'm going to fix it in the next update

**Comment by Overmiind** [comment]
It has been fixed in commit https://github.com/Overmiind/Puppeteer-sharp-extra/commit/7426092fd118de6a235d898c7f3609d1dc5aee33)[7426092fd118de6a235d898c7f3609d1dc5aee33]
