### ISSUE TITLE
Doesn't work with .NETFramework 4.7.2

### ISSUE THREAD

**Issue by i7solar** [Overmiind/Puppeteer-sharp-extra#10]
Anyway you can add support for .NETFramework 4.7.2

**Comment by danmohn** [comment]
Agreed.  Puppeteer Sharp is Net Standard 2.0 compatible, this is only NetCoreApp V3.1.

**Comment by Overmiind** [comment]
You right, I will change the target framework to Net Standard 2.0 this week.

**Comment by Overmiind** [comment]
Migrated to net standard 2.0 in version 1.2.0.
