### ISSUE TITLE
About Google Login

### ISSUE THREAD

**Issue by yiming1995** [Overmiind/Puppeteer-sharp-extra#12]
Hello, Thank you for this package.
I have tried to login gmail using this package, but I can't login.
Maybe, google detects webdriver.
How to solve this problem?

**Comment by Overmiind** [comment]
Hello, I tried to login in gmail with this code, and it's working. Make sure you're using the stealth plugin and try to use a proxy.
```c#
var extra = new PuppeteerExtra();
// Use stealth plugin
extra.Use(new StealthPlugin())
// Launch the puppeteer browser with plugins
var browser = await extra.LaunchAsync(new LaunchOptions()
{
    Headless = true,
    ExecutablePath = @"C:\chrome\chrome.exe"
})
var page = (await browser.PagesAsync()).First();
await page.GoToAsync("https://gmail.com");
var login = await page.QuerySelectorAsync("#identifierId");
await login.TypeAsync("login");
var next = await page.QuerySelectorAsync("div[class=VfPpkd-RLmnJb");
await next.ClickAsync();
var password = await page.WaitForSelectorAsync("input[type=password");
await page.WaitForTimeoutAsync(2000);
await password.TypeAsync("password");
next = await page.QuerySelectorAsync("div[class=VfPpkd-RLmnJb");
await next.ClickAsync();
await page.WaitForTimeoutAsync(5000);
await page.ScreenshotAsync("test.jpg");
await browser.CloseAsync();
```

**Comment by yiming1995** [comment]
Hi, Thank you for supporting.
I have got the same result.
Please check this image.
https://www.dropbox.com/s/0tak83qh76ouqbn/error.PNG?dl=0

**Comment by Overmiind** [comment]
Can you navigate to this page 'https://bot.sannysoft.com' in headless mode with the stealth plugin and take a screenshot?

**Comment by yiming1995** [comment]
https://www.dropbox.com/s/inrn0gbkcfd7dgc/test.jpg?dl=0
Please check again.

**Comment by Overmiind** [comment]
It's weird because I'm getting a different result. Do you use the latest version of puppeteer extra? Maybe you can send me your entire project? 
![image](https://user-images.githubusercontent.com/32036191/106647651-48791680-65a0-11eb-83a5-25203f1db500.png)

**Comment by yiming1995** [comment]
[WpfApp4.zip](https://github.com/Overmiind/Puppeteer-sharp-extra/files/5915706/WpfApp4.zip)
Thank you for reply. Please check this.

**Comment by Overmiind** [comment]
As I see you're using net framework 4.7.2. I tested on that framework version and it's working as well. Can you create new Net Core 3.1 project and test it again? Also, try to download chromium using browser fetcher
```c# 
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
 ```

**Comment by yiming1995** [comment]
Yes. At Net Core 3.1, it is running well. Thanks a lot.
Excuse me, I have a question. What is difference between 4.7.2 and 3.1 when use extra plugins?

**Comment by Overmiind** [comment]
I guess it's just a weird bug that I can't explain :) When I'm creating 4.7.2 project it's working as well as 3.1. I recommend using .net core instead of net framework. 
Thank's for your feedback.

**Comment by yiming1995** [comment]
Thank you for supporting.

**Comment by avlobn** [comment]
now not work, work only  Headless = false
if Headless = true,  google say = browser not secure,
there is a solution?

**Comment by shunqiziran888** [comment]
关于google login (登录), Headless=true  插件版本改成1.2.1即可正常工作 @Overmiind @avlobn @yiming1995
