### ISSUE TITLE
Webdriver test is not bypass validation 

### ISSUE THREAD

**Issue by clement128** [Overmiind/Puppeteer-sharp-extra#13]
I am using this https://infosimples.github.io/detect-headless/ for testing. Unfortunately `Webdriver` is failed.

![image](https://user-images.githubusercontent.com/53804808/107464486-5b40ac00-6b9b-11eb-8f38-1eac6bd7c816.png)

the node version [puppeteer-extra-plugin-stealth](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth) work on difference approach.

**Comment by Overmiind** [comment]
Hello, fixed by version 1.2.1, please update it from NuGet. #15
