### ISSUE TITLE
Looking for a developer to port the rest of the node.js library to c#

### ISSUE THREAD

**Issue by emorell96** [Overmiind/Puppeteer-sharp-extra#18]
Hi Overmiind,

I couldn't find any other means of contacting you so I decided to open an issue on your repository hoping to grab your attention. 

I am looking for someone with experience in c# and puppeteer to help me port the rest of the node.js library. Of course I'd be paying you to consult and extend this library with the latest evasions available in the node.js code.

Let me know if that is something that might interest you, and I'd be happy to share more details over a more private means of communication.

**Comment by Overmiind** [comment]
Hi, we can discuss it on my email - oleg26578@gmail.com. Please send me what would you like to extend and port from node js.
