### ISSUE TITLE
Name 'Task' conflicts with System.Threading.Tasks.Task

### ISSUE THREAD

**Issue by Telavian** [Overmiind/Puppeteer-sharp-extra#2]
The usage of PuppeteerExtraSharp.Plugins.Recaptcha.Provider.AntiCaptcha.Task conflicts with the built in Task found in System.Threading.Tasks.Task.

This means anything that uses tasks and this project will have to be careful to make sure the auto added using statements are correct.

I would expect all .Net developers when they see 'Task' expect the standard .net one not a seperate one.

Consider renaming or making that internal.

**Comment by Overmiind** [comment]
It has been fixed in commit 7426092
