### ISSUE TITLE
Error When Running Demo Code Examples

### ISSUE THREAD

**Issue by dawningtruth** [Overmiind/Puppeteer-sharp-extra#28]
Hi,
I have tried the demo code for PuppeteerExtraSharp and keep getting the error below. Any suggestions:
ERROR:
System.IO.FileNotFoundException HResult=0x80070002 Message=Process revision is not downloaded. Run BrowserFetcher.DownloadAsync or download the process manually Source=PuppeteerSharp StackTrace: at PuppeteerSharp.Launcher.ResolveExecutablePath() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 212 at PuppeteerSharp.Launcher.GetOrFetchBrowserExecutable(LaunchOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 171 at PuppeteerSharp.Launcher.<LaunchAsync>d__8.MoveNext() in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Launcher.cs:line 52 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at PuppeteerExtraSharp.PuppeteerExtra.&lt;LaunchAsync&gt;d__2.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter1.GetResult() at Learn_PuppeteerExtraSharp.Program.<Main>d__0.MoveNext() in C:\Users\Dave\Dropbox\Code Learn\Learn PuppeteerExtraSharp\Learn PuppeteerExtraSharp\Learn PuppeteerExtraSharp\Program.cs:line 25
This exception was originally thrown at this call stack: [External Code] Learn_PuppeteerExtraSharp.Program.Main(string[]) in Program.cs
CODE:

`using PuppeteerExtraSharp; using PuppeteerExtraSharp.Plugins.AnonymizeUa; using PuppeteerExtraSharp.Plugins.ExtraStealth; using PuppeteerSharp; using System; using System.Threading.Tasks;
namespace Learn_PuppeteerExtraSharp { class Program { static async Task Main(string[] args) { Console.WriteLine("Hello Pupeteer Extra Sharp");
        // Initialization plugin builder
        var extra = new PuppeteerExtra();

        // Use stealth plugin
        var puppeteerExtra = new PuppeteerExtra().Use(new AnonymizeUaPlugin()).Use(new StealthPlugin());

        // Launch the puppeteer browser with plugins
        //ERROR OCCURS ON THE LINE BELOW
        var browser = await puppeteerExtra.LaunchAsync(new LaunchOptions()
        {
            Headless = true
        });

        // Create a new page
        var page = await browser.NewPageAsync();

        await page.GoToAsync("http://google.com");

        // Wait 2 second
        await page.WaitForTimeoutAsync(2000);

        // Take the screenshot
        await page.ScreenshotAsync("extra.png");
    }
}
}`

**Comment by yarns123** [comment]
You need install also PuppeteerSharp - then it works fine,

**Comment by dawningtruth** [comment]
Thx, I have tried that option and it still does not work.

Please find my Project attached. Perhaps it will help with the diagnosis.

[Learn PuppeteerExtraSharp.zip](https://www.dropbox.com/s/tt9w96ollqc773v/Learn%20PuppeteerExtraSharp.zip?dl=0)

**Comment by Overmiind** [comment]
Hi, you should specify the executable path of your chrome browser. Here is the example: 
```c#
var browser = await puppeteerExtra.LaunchAsync(new LaunchOptions()
{
    Headless = true,
    ExecutablePath = @"C:\chromium\chrome.exe" // <- specify you own path 
});
```

**Comment by dawningtruth** [comment]
Fantastic. Thx, it worked!
