### ISSUE TITLE
How do I delete enabled evasions?

### ISSUE THREAD

**Issue by stephenerik** [Overmiind/Puppeteer-sharp-extra#29]
Hi,

I'm trying to replicate the following js code in Puppeteer-sharp-extra. Does anyone know how I delete the 2 enabled evasions?

const StealthPlugin = require("puppeteer-extra-plugin-stealth")();
StealthPlugin.enabledEvasions.delete("chrome.runtime");
StealthPlugin.enabledEvasions.delete("iframe.contentWindow");
puppeteer.use(StealthPlugin);

Thanks in advance.

**Comment by fergus3000** [comment]
I had the same question. Looking at the source code, stealthplugin.cs in particular, I don't believe it's possible.

**Comment by Overmiind** [comment]
Fixed by package version 1.3.2
