### ISSUE TITLE
Missing or invalid evasions

### ISSUE THREAD

**Issue by Telavian** [Overmiind/Puppeteer-sharp-extra#4]
In comparison to the original node.js library this one has some difference.

Node JS, C#
Chrome.csi, Chrome.Sci
Chrome.loadTimes, Missing
sourceurl, Missing
window.outerdimensions, Missing

Are you open to pull requests?

**Comment by Overmiind** [comment]
Yes I would appreciate it to get pull request from you because I don't have much time at this moment

**Comment by Overmiind** [comment]
I have added all plugins except sourceurl. What I see is that this plugin overrides "send" method in CDP session class but in sharp this method is not overridable and I don't know how to do it. If you could help with solving this problem I would very appreciate it

**Comment by Telavian** [comment]
I can look. I certainly did plan on helping. Work has been chaotic.

**Comment by Overmiind** [comment]
SourceURL was added by #20.
