### ISSUE TITLE
AnonymizeUaPlugin not working in puppetsharp 7.1.0

### ISSUE THREAD

**Issue by Khalmz** [Overmiind/Puppeteer-sharp-extra#40]
Method not found: 'System.Threading.Tasks.Task PuppeteerSharp.Page.SetUserAgentAsync(System.String)'.

**Comment by namilkimfree** [comment]
Fixed this Issue

**Comment by Overmiind** [comment]
Fixed by [R3D4NG3L](https://github.com/Overmiind/Puppeteer-sharp-extra/pull/49)
Please update the NuGet package version of Puppeteer Extra Sharp to 2.0.
