### ISSUE TITLE
Help in Lunching

### ISSUE THREAD

**Issue by mostafakamelomarrslan** [Overmiind/Puppeteer-sharp-extra#44]
System.MissingMethodException: 'Method not found: 'System.Threading.Tasks.Task`1<PuppeteerSharp.Browser> PuppeteerSharp.Puppeteer.LaunchAsync(PuppeteerSharp.LaunchOptions, Microsoft.Extensions.Logging.ILoggerFactory)'.'

**Comment by KoalaBear84** [comment]
More info will be helpful, looks like a exact duplicate of my ticket. #42

**Comment by namilkimfree** [comment]
Fixed this Issue

**Comment by Overmiind** [comment]
Fixed by [R3D4NG3L](https://github.com/Overmiind/Puppeteer-sharp-extra/pull/49)
Please update the NuGet package version of Puppeteer Extra Sharp to 2.0.
