### ISSUE TITLE
Cloudflare Challenge still detecting Puppeteer

### ISSUE THREAD

**Issue by ghost** [Overmiind/Puppeteer-sharp-extra#53]
Puppeteer-sharp-extra did not help bypassing Cloudflare Challenge's Puppeteer detection. After passing captcha, the page reloads and ask for captcha again and again. I don't use ReCaptcha plugin, I just want to solve captcha manually, then save `cf_clearance` cookie temporary until it is invalid

**Comment by KoalaBear84** [comment]
That is indeed strange, we are also blocked, but maybe because I'm located in The Netherlands? I don't think anyone here ever accessed the site 🙃
